/control/alias ViewPointThetaPhi  30 30
/control/alias VisuOnOff  visu
/control/alias SourceActivity  100. Bq
/control/alias Nb_Detectors  2
/control/alias CrystalMaterial  NaI
/control/alias PhantomMaterial  Lead
/control/alias PhanRmax  18 mm
/control/alias PhanRmin  15mm
/control/alias Phan_Source_Pos  0.0 0.0 0.0 mm
/control/alias SourceVolMaterial  Water
/control/alias SourceEnergy  100 keV
/control/alias RootFileName  Coin_Chan_{Nb_Detectors}_{PhantomMaterial}
